version: "3.8"
services:
    app:
        build: .
        container_name: kafka-php-app
        working_dir: /var/www/
        volumes:
            - ./docker/php/conf.d:/usr/local/etc/php/conf.d
            - ./:/var/www
        networks:
            - kafka-php-network
    db:
        image: mysql:5.7
        container_name: kafka-mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: kafka-php8
            MYSQL_USER: kafka-php8
            MYSQL_PASSWORD: 12345
        networks:
            - kafka-php-network
    nginx:
        image: nginx:alpine
        container_name: kafka-php-nginx
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - kafka-php-network
    zookeeper:
        image: "bitnami/zookeeper:latest"
        container_name: kafka-php-zookeeper
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - kafka-php-network
    kafka:
        image: "bitnami/kafka:latest"
        container_name: kafka-php-kafka
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
        networks:
            - kafka-php-network
networks:
    kafka-php-network:
        driver: bridge
